enum InstitutionType {
  DOCTORSOFFICE = 'DOCTORSOFFICE',
  HOSPITAL = 'HOSPITAL',
  INSURANCE = 'INSURANCE',
  STATEHA = 'STATEHA',
  GOVHA = 'GOVHA',
  BIOTECHCOMPANY = 'BIOTECHCOMPANY',
  UNIVERSITY = 'UNIVERSITY',
}

export default InstitutionType;
